### ISSUE TITLE
[Bug]: Auras Disappear in Duty

### ISSUE THREAD

**Issue by Boxx1247** [DelvUI/DelvCD#69]
### What are you trying to do?

[dalamud.log](https://github.com/user-attachments/files/17804325/dalamud.log)

### What is the expected behavior?

Auras dont disappear

### What actually happened?

Auras disappear

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvCD.

**Comment by Tischel** [comment]
Released a fix in v1.2.0.1 so the plugin doesn't crash when this occurs.

The root cause of this is the fact that some icons game files where moved in patch 7.1.
You will need to manually update your auras so the icons are fetched again.
You can do this by simply re-typing the status/action name/id on each aura.
